#!/bin/bash
# zhchen@redhat.com

testList='/distribution/reservesys Attr: pkg=distrbution topo=singleHost time=12h ssched=no type=Functioal'

Usage()
{
	echo -e "Usage: bkr-reservesys <distro> [-- bkr-workflow options]"
	echo -e "Call runtest to submit a /distribution/reservesys job to beaker"
}

[ "$#" = 0 ] && { Usage; exit 1; }
[ "$1" = "-h" -o "$1" = "--help" ] && { Usage; exit 0; }

run_option=$(sed 's#\(^.*\)-- \(.*$\)#\1#' <<< "$@")
[ -z "$run_option" ] && {
	echo "Error: no distro specified"
	Usage; exit 1
}

bkr_option=$(sed 's#'"$run_option"'##' <<< "$@")
echo "$testList" | runtest $run_option - -- ${bkr_option#-- } -cmd='echo -e "redhat\nredhat"|passwd'
