#!/bin/bash
#autor jiyin@redhat.com

tmpf=/tmp/$$tmp.txt

# depend pkg install
which bugzilla &>/dev/null || {
	echo "[info] need install curl command ..."
	yum install -y python-bugzilla
}

hspace() {
	for ((i = 0; i < $1; i++)); do echo -n "&nbsp;"; done
}

bzsearch() {
    #Usage $0 <productName>
    local P=${1}; shift
    echo -e "Buglist with blocker+ or with key:{Regression||ZStream||FutureFeature||TestBlocker}" >&2
    echo -e "\nProduct: $P" >&2
    for  U  in  $ulist; do
        bzlist=$( {
        bugzilla query -q $U@redhat.com -p "$P" -t MODIFIED,ON_QA,POST  --flag=blocker \
            --boolean_query=cf_verified-notregexp-SanityOnly \
            --outputformat="%{qa_contact} %{cf_verified} %{keywords} %{flags} %{id} %{priority} %{status} %{summary}" 2>/dev/null
        bugzilla query -q $U@redhat.com -p "$P" -t MODIFIED,ON_QA,POST  -k TestBlocker -k FutureFeature -k Regression -k ZStream \
            --boolean_query=cf_verified-notregexp-SanityOnly \
            --outputformat="%{qa_contact} %{cf_verified} %{keywords} %{flags} %{id} %{priority} %{status} %{summary}" 2>/dev/null
        } | sort -u | sed '/^$/d' )
        [ -z "${bzlist}" ] && continue
        echo "${bzlist}"
    done
}
saved_search() {
    #Usage $0 <searchName [shareid]> [reportlink]
    local sname=$1
    local shareid= reportlink=
    [ -n "$2" ] && optShareid="--savedsearch-sharer-id=$2"
    [ -n "$3" ] && reportlink="reportlink->$3"

    echo -e "SearchName->$sname $reportlink" >&2
    bzlist=$(bugzilla query --savedsearch=$sname $optShareid \
        --outputformat="%{qa_contact} %{cf_verified} %{keywords} %{flags} %{id} %{priority} %{status} %{summary}" 2>/dev/null)
    echo "$bzlist"
}
text_format() {
    unset bzAA; declare -A bzAA
    while read U bzinfo; do bzAA[$U]+=${bzinfo}$'\n'; done

    for U in $ulist; do
        U+="@redhat.com"
        [ -z "${bzAA[$U]}" ] && continue
        N=$(wc -l <<<"${bzAA[$U]}")
        printf "\n* %-16s (%d bugs):\n"  "$U"  $((N-1))
        while read verified key flags id level stat info; do
            [ -z "$id" ] && continue
            echo "$id $level $stat $info; $key $flags $verified"|sed 's/^/  - /'
        done <<<"${bzAA[$U]}"
    done
}
html_format() {
    unset bzAA; declare -A bzAA
    while read U bzinfo; do bzAA[$U]+=${bzinfo}$'\n'; done
    for U in $ulist; do
        U+="@redhat.com"
        [ -z "${bzAA[$U]}" ] && continue
        N=$(wc -l <<<"${bzAA[$U]}")
        echo "<br>"
        echo "<table bgcolor=#E0FFFF>"
        echo "<tr>"
        echo "<td><b>$U - ($((N-1)) bugs):</b></td>"
        echo "</tr>"
        echo "</table>"
        echo "<table bgcolor=#E0FFFF border=1>"
        while read verified key flags id level stat info; do
            [ -z "$id" ] && continue
            echo "<tr>"
            echo "<td><a href=\"https://bugzilla.redhat.com/$id\">bz$id</a></td>"
            echo "<td>$level</td>"
            echo "<td>$stat</td>"
            echo "<td>$info</td>"
            echo "<td>$flags</td>"
            echo "<td>$verified</td>"
            #echo "<td>$key</td>"
            echo "</tr>"
        done <<<"${bzAA[$U]}"
        echo "</table>"
    done
}

: <<COMM
saved_search rhel66bugs 208114
COMM

ulist="eguan cye zlang xzhou xifeng jiyin fs-qe"
to=fs-qe-dev@redhat.com
test "$1" = "mail" && {
    bzsearch "Red Hat Enterprise Linux 6" | html_format |
        sendmail.sh -p '[Reminder: BZ/FS] ' -f bugzilla@redhat.com -t "$to" - " RHEL-6 bugs ..." -H
    bzsearch "Red Hat Enterprise Linux 7" | html_format |
        sendmail.sh -p '[Reminder: BZ/FS] ' -f bugzilla@redhat.com -t "$to" - " RHEL-7 bugs ..." -H
}

ulist="haliu zhchen kzhang ypei lxin zshi weliu network-qe honli infiniband-qe jipan jshao"
to=kernel-qa@redhat.com
test "$1" = "mail" && {
    bzsearch "Red Hat Enterprise Linux 6" | html_format |
        sendmail.sh -p '[Reminder: BZ/Network] ' -f bugzilla@redhat.com -t "$to" - " RHEL-6 bugs ..." -H
    bzsearch "Red Hat Enterprise Linux 7" | html_format |
        sendmail.sh -p '[Reminder: BZ/Network] ' -f bugzilla@redhat.com -t "$to" - " RHEL-7 bugs ..." -H
}

\rm ${tmpf}*

