#!/bin/bash
#author: jiyin@redhat.com

# https://en.wikichip.org/wiki/irc/colors
ircBold=$'\x02'
ircItalics=$'\x1D'
ircUnderline=$'\x1F'
ircReverse=$'\x16'
ircPlain=$'\x0F'

ircWhite=$'\x03'00
ircBlack=$'\x03'01
ircNavy=$'\x03'02
ircGreen=$'\x03'03
ircRed=$'\x03'04
ircMaroon=$'\x03'05
ircPurple=$'\x03'06
ircOlive=$'\x03'07
ircYellow=$'\x03'08
ircLightGreen=$'\x03'09
ircTeal=$'\x03'10
ircCyan=$'\x03'11
ircRoyalblue=$'\x03'12
ircMagenta=$'\x03'13
ircGray=$'\x03'14
ircLightGray=$'\x03'15

mkdir -p /var/cache/kernelnvrDB
pushd /var/cache/kernelnvrDB  >/dev/null

from="kernel monitor <from@redhat.com>"
mailTo=fs@redhat.com
mailCc=net@redhat.com
kgitDir=/home/yjh/ws/code.repo
VLIST="6 7 8"
latestKernelF=.latest.kernel
kfList=$(eval echo $latestKernelF-{${VLIST// /,}})
#echo $kfList
debug=$1

searchBrewBuild 'kernel(-alt)?-[-.0-9]+el'"[${VLIST// /}]".?'$' >.kernelList
test -n "`cat .kernelList`" &&
	for V in ${VLIST}; do
	    L=$(egrep 'kernel-alt-[-.0-9]+el'$V .kernelList | head -n4)
	    echo "$L" >${latestKernelF}-$V.tmp
	    L=$(egrep 'kernel-[-.0-9]+el'$V .kernelList | head -n4)
	    echo "$L" >>${latestKernelF}-$V.tmp
	done

for f in $kfList; do
	[ ! -f ${f}.tmp ] && continue
	[ $(stat -c %s ${f}.tmp) = 0 ] && continue

	[ ! -f ${f} ] && {
		mv ${f}.tmp ${f}
		continue
	}
	[ -n "$debug" ] && {
		echo
		cat ${f}.tmp
		diff -pNur ${f} ${f}.tmp | sed 's/^/\t/'
		rm -f ${f}.tmp
		continue
	}

	V=${f%*-}
	newkernel=
	available=1

	p=${PWD}/${f}.patch
	diff -pNur $f ${f}.tmp >$p && continue
	sed -i '/^[^+]/d;/^+++/d' $p
	grep '^+[^+]' ${p} || continue
	newkernel=$(sed 's/^+//' ${p})

	url=https://home.corp.redhat.com/wiki/rhel${V}changelog
	url=http://patchwork.lab.bos.redhat.com/status/rhel${V}/changelog.html
	urlAlt=http://patchwork.lab.bos.redhat.com/status/rhel-alt-7.5/changelog.html
	for nvr in $newkernel; do
		[[ -z "$nvr" || "$nvr" =~ ^\+\+\+ ]] && continue
		changeUrl=$url
		[[ $nvr =~ kernel-alt ]] && changeUrl=$urlAlt

		for chan in "#fs-qe" "#network-qe"; do
			ircmsg.sh -s fs-qe.usersys.redhat.com -p 6667 -n testBot -P rhqerobot:irc.devel.redhat.com -L testBot:testBot -C "$chan" \
				"${ircBold}${ircRoyalblue}{Notice}${ircPlain} new kernel: $nvr    # $changeUrl"
		done
	done

	# send email
	echo >>$p
	echo "#-------------------------------------------------------------------------------" >>$p
	echo "# $url" >>$p
	echo "# $urlAlt" >>$p
	for nvr in $newkernel; do
		echo -e "{Info} ${nvr} changelog read from pkg:"
		downloadBrewBuild $nvr --arch=src
		[ -f ${nvr}.src.rpm ] || {
			available=0
		}
		if [[ $nvr =~ kernel-alt ]]; then
			LANG=C rpm -qp --changelog ${nvr}.src.rpm >kernel-alt-changeLog-$V
		else
			LANG=C rpm -qp --changelog ${nvr}.src.rpm >changeLog-$V
		fi
		\rm ${nvr}.src.rpm

		vr=${nvr/kernel-/}
		vr=${vr/alt-/}
		sed -r -n "/\*.*\[${vr}\]/,/^$/{p}" kernel-alt-changeLog-$V changeLog-$V >changeLog
		sed -n '1p;q' changeLog
		grep '^-' changeLog | sort -k2,2
		echo
	done >>$p

	echo -e "\n\n#===============================================================================" >>$p
	echo -e "\n#Generated by cron latestKernelCheck" >>$p
	echo -e "\n#cur:" >>$p; cat $f.tmp >>$p
	echo -e "\n#pre:" >>$p; cat $f     >>$p
	echo -e "\n\n# the Covsan task info:" >>$p; cat Covscan.$V >>$p

	[ $available = 1 ] && {
		sendmail.sh -p '[Notice] ' -f "$from" -t "$mailTo" -c "$mailCc" "$p" ": new RHEL${V} kernel available"  &>/dev/null
		#cat $p
		mv ${f}.tmp ${f}
	}

	rm -f $p
done

popd  >/dev/null

