#!/bin/bash
#
# Synchronize tasks between SERVER/Client jobs
# on multihost machines.
#
export TASKORDER=$(expr $TASKORDER + 1)
if rpm -q firewalld &>/dev/null  && systemctl is-active --quiet firewalld; then
    if ! firewall-cmd --zone=$(firewall-cmd --permanent --get-default-zone 2>/dev/null || echo "public") --query-port=6776/tcp &>/dev/null; then
        firewall-cmd --permanent --zone=$(firewall-cmd --permanent --get-default-zone 2>/dev/null || echo "public") --add-port=6776/tcp --quiet
        firewall-cmd --reload --quiet
    fi
fi
if [[ "$RSTRNT_STANDALONE" != yes ]]; then
	if [ -z "$SERVERS" ] || [ -z "$CLIENTS" ]; then
	    echo "Skipping Multihost sync .. SERVERS/CLIENTS roles not set"
	else
	    echo "Multihost synchronization for Servers=$SERVERS Clients=$CLIENTS"
	    rstrnt-sync-set -s DONE
	    rstrnt-sync-block -s DONE --retry 30 $SERVERS $CLIENTS $DRIVER
	fi
else
	[[ -z "$RSTRNT_NOPLUGINS" ]] && 
		{ testmark __finallyDone; testwaitfor __finallyDone $SERVERS $CLIENTS; rm -rf /tmp/testmark; } 2>/dev/null
fi
