#!/bin/bash

#
# If the following variables aren't defined try and guess them from the system
#

. /usr/share/restraint/plugins/helpers

rstrnt_info "*** Running Plugin: $0"

if [ -z "$HOSTNAME" ]; then
   HOSTNAME=$(hostname)
fi

if [ -z "$RSTRNT_OSARCH" ]; then
        RSTRNT_OSARCH=$(uname -i)
fi

if [ -z "$RSTRNT_OSMAJOR" ]; then
        RSTRNT_OSMAJOR=$(cat /etc/redhat-release | sed -e 's/\(.*\)release\s\([0-9]*\).*/\1\2/; s/\s//g')
fi

# see: https://restraint.readthedocs.io/en/latest/remove_rhts.html#legacy-rhts-task-environment-variables
# if restraint runs in un-compatable mode, and we still use old ENV name
if [[ -n "$RSTRNT_JOBID" && -z "$JOBID" ]]; then
	export RHTS_COMPAT=no
	export ARCH="$RSTRNT_OSARCH" \
	DISTRO="$RSTRNT_OSDISTRO" \
	FAMILY="$RSTRNT_OSMAJOR" \
	JOBID="$RSTRNT_JOBID" \
	REBOOTCOUNT="$RSTRNT_REBOOTCOUNT" \
	RECIPESETID="$RSTRNT_RECIPESETID" \
	RECIPEID="$RSTRNT_RECIPEID" \
	RECIPETESTID="$RSTRNT_RECIPEID" \
	SUBMITTER="$RSTRNT_OWNER" \
	TASKID="$RSTRNT_TASKID" \
	TESTID="$RSTRNT_TASKID" \
	TESTNAME="$RSTRNT_TASKNAME" \
	TEST="$RSTRNT_TASKNAME" \
	TESTPATH="$RSTRNT_TASKPATH" \
	VARIANT="$RSTRNT_OSVARIANT"
fi
[[ -z "$KILLTIMEOVERRIDE" ]] && export KILLTIMEOVERRIDE=$((RSTRNT_MAXTIME+600))

if [[ "$RSTRNT_STANDALONE" = yes ]]; then
	for host in $SERVERS $CLIENTS; do
		if [[ $host = $HOSTNAME ]]; then
			break
		elif [[ ${host%%.*} = ${HOSTNAME%%.*} ]]; then
			export HOSTNAME=$host
			break
		fi
	done
fi

exec "$@"
