#!/bin/bash
# Print commands to install-xxx or do something
# Author : Zhenjie Chen <zhchen@redhat.com>
# Require: xsel

# Usage  : run this script locally, it will print related commands to the stand
#          output, and save to your clipboard. You can easily paste and execute
#          the commands on your target system

# Notes  : click middle mouse button or type <shift>+insert to paste

install-iperf()
{
	VERSION=2.0.5

	cat <<- EOF
	wget http://jaist.dl.sourceforge.net/project/iperf/iperf-2.0.5.tar.gz &&
	tar zxvf iperf-${VERSION}.tar.gz &&
	pushd iperf-${VERSION} &&
	./configure && make && make install &&
	popd
	EOF
}

install-netperf()
{
	VERSION=2.6.0
	cat <<- EOF
	wget ftp://ftp.netperf.org/netperf/netperf-${VERSION}.tar.bz2 &&
	tar -jxvf netperf-${VERSION}.tar.bz2 &&
	pushd netperf-${VERSION} &&
	./configure && make && make install &&
	pushd
	EOF
}

install-network-common()
{
	cat <<- EOF
	yum install -y kernel-kernel-networking-common
	source /mnt/tests/kernel/networking/common/include.sh
	EOF
}

install-beakerlib()
{
	cat <<- EOF
	yum install -y wget
	wget -O /etc/yum.repos.d/beaker-client.repo http://download.lab.bos.redhat.com/beakerrepos/beaker-client-RedHatEnterpriseLinux.repo
	rpm -ivh http://qafiler.bos.redhat.com/qa-tools/deprecated/rhts/support/rhts-release.noarch.rpm
	yum install -y rhts-test-env beakerlib rhts-devel rhts-python beakerlib-redhat beaker-client beaker-redhat
	EOF
}

install-beaker-task-repo()
{
	cat <<- EOF
	cat <<- _EOF > /etc/yum.repos.d/beaker-tasks.repo

	[beaker-tasks]
	name=beaker-tasks
	baseurl=http://beaker.engineering.redhat.com/rpms
	enabled=1
	gpgcheck=0
	skip_if_unavailable=1
	_EOF
	EOF
}

install-kernel()
{
# getcmd-install-kernel 2.6.18-371
# getcmd-install-kernel 3.10.0-123.6.2
	major=${1%-*}
	minor=${1#*-}
	arch=${2:-"x86_64"}
	URL="http://download.devel.redhat.com/brewroot/packages/kernel"
	case $major in
		2.6.18)
			minor+=".el5"
			fw="kernel-doc-$major-$minor.noarch.rpm"
			;;
		2.6.32)
			minor+=".el6"
			fw="kernel-firmware-$major-$minor.noarch.rpm"
			;;
		3.10.0)
			minor+=".el7"
			fw="kernel-doc-$major-$minor.noarch.rpm"
			;;
		*)
			echo "error, invalid kernel version"
			exit 1
			;;
	esac

	kernel="kernel-$major-$minor.$arch.rpm"

	cat <<- EOF
	wget $URL/$major/$minor/noarch/$fw -O $fw &&
	wget $URL/$major/$minor/$arch/$kernel -O $kernel &&
	rpm -ivh --force $fw &&
	rpm -ivh --force $kernel &&
	reboot
	EOF
}

eth-info()
{
	cat <<- 'EOF'
	for ethX in `ls /sys/class/net/`; do
		if [ "$ethX" = lo ]; then continue; fi
		driver=`ethtool -i $ethX | awk '/driver:/ {print $2}'`
		ip=`ip addr show $ethX | awk '/inet/ {print $2}'`
		mac=`cat /sys/class/net/$ethX/address`
		echo $ethX, driver: $driver, mac: $mac, $ip
	done

	EOF
}

progname=${0##*/}
[ _getcmd = "$progname" ] && { echo "invalid program name" ; exit 1; }

progname=${progname/getcmd-/}
$progname "$@" | tee >(xsel)
