#!/bin/bash

echo -e "argc=\E[45m$(($#+1))\E[0m"
for ((i=0; i<=$#; i++)); do echo -e "argv[$i]: \E[44m${!i}\E[0m"; done

echo
echo '[echo "$*"]'
echo -e "\E[44m""$*""\E[0m"

echo
echo '[echo "$@"]'
echo -e "\E[44m""$@""\E[0m"

echo
echo '[cat <(echo "$*")]'
echo -ne "\E[44m"
cat <(echo "$*")
echo -ne "\E[0m"
