#!/bin/bash
# bugzilla credential will never be expired

username=$1
if [[ -z "$username" ]]; then
	read -p "Username: " username
fi
read -s -p "Password: " password
echo

_login() {
	bugzilla login $username $password > /tmp/blogin-$USER.log 2>&1
	if [ $? -ne 0 ] ; then
		cat /tmp/blogin-$USER.log
		cat /tmp/blogin-$USER.log |
		mail -s "blogin(`hostname -s`): login error" $username
		return 1
	fi
}

forever_login() {
	while : ; do
		sleep 8h
		_login
	done
}

# make sure password is correct
_login || exit 1

# then function can run in background forever, untill you kill it
trap "" HUP
forever_login & pid=$!

echo $pid | tee /tmp/blogin-$USER.pid

# and the script can exit.
exit 0
