#!/bin/bash
#author jiyin@redhat.com

dburl=http://download.devel.redhat.com/qa/rhts/lookaside/distro-rpmsdata
dbroot=/var/cache/distroInfoDB/rpmsdata

Pkg=
Arch=x86_64
Variant=Workstation
P=${0##*/}

Usage() {
	cat >&2 <<-EOF
	Usage:
	    $P <-p pkgName|pattern> [-d distroName|pattern] [-a <arch>|-v <variant>] [--dbroot]

	Example:
	    $P -d \$distro -p \$pkg      #1 get package \$pkg's version on \$distro
	    $P -d \$distro              #2 get package kernel's version on \$distro
	    $P -p \$pkg                 #3 get package \$pkg's version on all available distros

	    $P -d \$distro -trees       #4 or --distrotrees, get detail info of distro
	    $P -d \$distro -rpmsinfo    #5 show distro's package list in json format
	    $P -d \$distro -composeinfo #6 show distro's compose info

	    $P --dlist                 #7 or --distrolist, get available distro list
	EOF
}
Debug() {
	[[ -n "$debug" ]] && { echo "{debug} $@" >&2; }
}

[[ $# = 0 ]] && {
	Usage
	exit 1
}

_at=`getopt -o hnp:d:a:v:lD \
	--long help \
	--long rpmsinfo \
	--long composeinfo \
	--long dbroot: \
	--long distrotrees --long trees --long url \
	--long distrolist --long dlist \
    -a -n "$0" -- "$@"`
eval set -- "$_at"
while true; do
	case "$1" in
	-h|--help)      Usage; shift 1; exit 0;;
	-n) nocolor=yes; shift 1;;
	-p) Pkg=$2; shift 2;;
	-d) Distro=$2; shift 2;;
	-a) Arch=$2; shift 2;;
	-v) Variant=$2; shift 2;;
	-l) long=yes; shift 1;;
	-D) debug=yes; shift 1;;
	--url|--trees|--distrotrees) getdistrotrees=yes; shift 1;;
	--rpmsinfo) getrpmsinfo=yes; shift 1;;
	--composeinfo) getcomposeinfo=yes; shift 1;;
	--dbroot) dbroot=$2; shift 2;;
	--dlist|--distrolist) getdistrolist=yes; shift 1;;
	--) shift; break;;
	esac
done

dbpath=$dburl
if [[ -d $dbroot ]]; then
	dbpath=file://$(readlink -f $dbroot)
fi
Debug "using data source: $dbpath"

[[ -n "$getdistrolist" ]] && {
	curl -Lsf $dbpath/distro.list
	exit $?
}

Pkg=${Pkg:-$1}
RawPkg=$Pkg
Pkg=${Pkg:-^kernel-[0-9]}
Pkg="[^/]*${Pkg}[^/]*"
[[ ${Pkg:0:6} = '[^/]*^' ]] && Pkg="${Pkg:6}"
[[ ${Pkg: -6} = '$[^/]*' ]] && Pkg="${Pkg:0:-6}"
Distro=${Distro:-$2}
Distro=${Distro#/}

[[ -n "$Distro" ]] && {
	cachefile=$dbpath/${Distro// /_}.json.gz
	distrotrees_file=$dbpath/${Distro// /_}.distrotrees.gz

	[[ -n "$getrpmsinfo" ]] && {
		curl -Lsf $cachefile | zcat 2>/dev/null
		exit $?
	}

	[[ -n "$getdistrotrees" ]] && {
		curl -Lsf $distrotrees_file | zcat 2>/dev/null
		exit $?
	}

	[[ -n "$getcomposeinfo" ]] && {
		urls=$(curl -Lsf $distrotrees_file | zcat 2>/dev/null |
			awk '/https?:/ {
				if ($3 ~ "/compose/") {
					sub("/compose/.*$", "/compose/metadata", $3)
				} else if ($3 ~ "/released/") {
					sub("([^/]+/){3}$", "metadata", $3)
				}
				print $3
			}' | sort -u)
		for url in $urls; do
			curl -Lsf $url/composeinfo.json && break
		done
		exit $?
	}
}

[[ -z "${Pkg}" && "$Update" != yes ]] && {
	Usage
	exit 1
}

Debug "pkg:($Pkg) distro:($Distro) arch:($Arch) variant:($Variant)"
case "$Arch" in
	x86_64|i386|ppc64le|ppc64|s390x|aarch64) :;;
	*) echo "{warn} unknow arch '$Arch'" >&2;;
esac

# do search
mylist=$(curl -Lsf $dbpath/distro.list > >(egrep -i -- "${Distro}"))
ret=$?
[[ $ret != 0 ]] && {
	echo "something is wrong, curl return code $ret" >&2
}
while read distro; do
	[[ -z "$distro" ]] && continue
	cachefile=$dbpath/${distro// /_}.json.gz

	variant=$Variant
	[[ $distro = RHEL-8* ]] && {
		case $variant in Workstation|Client|Server|ComputeNode) variant=;; esac
	}

	Debug "distro:($distro) pkg:($Pkg) arch:($Arch) variant:($variant) @$cachefile"
	#result=$(curl -Lsf $cachefile | zcat 2>/dev/null |
	#	jq -r '.payload | with_entries(if .key == "manifest" then .key = "rpms" else . end)|.rpms|'".${variant:-[]}|.$Arch|.[]|.[].path" |
	#	grep -v source/tree |
	#	egrep "$Pkg")
	if [[ $distro =~ RHEL-?5 ]]; then
		distrotrees_file=$dbpath/${distro// /_}.distrotrees.gz
		read _ _ url _ < <(curl -Lsf $distrotrees_file | zcat 2>/dev/null | egrep https?://.*bos)
		Debug "egrep -o \">${RawPkg}-[0-9a-z\\._-]+\\.rpm<\" < <(curl -Lsf $url/Server)"
		result=$(egrep -o ">${RawPkg}-[0-9a-z\._-]+\.rpm<" < <(curl -Lsf $url/Server) | sed -e 's/^>//' -e 's/<$//')
	else
		Debug "egrep -o -i \"${variant:-[^\\\"]+}/($Arch)/os/(Packages|$variant)/([a-z]/)?(${Pkg})\.[0-9a-z_-]+\.rpm\" < <(curl -Lsf $cachefile|zcat 2>/dev/null)"
		result=$(egrep -o -i "${variant:-[^\"]+}/($Arch)/os/(Packages|$variant)/([a-z]/)?(${Pkg})\.[0-9a-z_-]+\.rpm" < <(curl -Lsf $cachefile|zcat 2>/dev/null))
	fi
	[[ -n "$result" ]] && {
		[[ -z "$nocolor" ]] && echo -e "=> \033[1;34m$distro\033[0m" || echo -n "$distro -> "
		if [[ $long = yes ]]; then
			echo "$result"|sed -e 's/^/    /'
		else
			echo "$result"|sed -e 's;.*/;;'
		fi
	}
done <<<"$mylist"

