#!/bin/bash
#author jiyin@redhat.com

dburl=http://download.devel.redhat.com/qa/rhts/lookaside/distro-rpmsdata
dbroot=/var/cache/distroInfoDB/rpmsdata

Pkg=
Arch=x86_64
Variant=Workstation
P=${0##*/}

Usage() {
	cat >&2 <<-EOF
	Usage:
	    $P <-p pkgName|pattern> [-d distroName|pattern] [-a <arch>|-v <variant>] [--dbroot]

	Example:
	    $P -d \$distro -p \$pkg      #1 get package \$pkg's version on \$distro
	    $P -d \$distro              #2 get package kernel's version on \$distro
	    $P -p \$pkg                 #3 get package \$pkg's version on all available distros

	    $P -d \$distro -labs        #4 get current labs info of distro
	    $P -d \$distro -trees       #4 or --distrotrees, get detail info of distro
	    $P -d \$distro -rpmsinfo    #5 show distro's package list in json format
	    $P -d \$distro -composeinfo #6 show distro's compose info

	    $P --dlist                 #7 or --distrolist, get available distro list
	EOF
}
Debug() {
	[[ -n "$debug" ]] && { echo "{debug} $@" >&2; }
}

[[ $# = 0 ]] && {
	Usage
	exit 1
}

_at=`getopt -o hnp:d:a:v:lD \
	--long help \
	--long oneline:: \
	--long rpmsinfo \
	--long composeinfo \
	--long dbroot: \
	--long labs \
	--long distrotrees --long trees --long url \
	--long distrolist --long dlist \
    -a -n "$0" -- "$@"`
eval set -- "$_at"
while true; do
	case "$1" in
	-h|--help) Usage; shift 1; exit 0;;
	--oneline) oneline=yes; maxperline=${2:-7}; shift 2;;
	-n) nocolor=yes; shift 1;;
	-p) Pkg=$2; shift 2;;
	-d) Distro=$2; shift 2;;
	-a) Arch=$2; shift 2;;
	-v) Variant=$2; shift 2;;
	-l) long=yes; shift 1;;
	-D) debug=yes; shift 1;;
	--labs) getlabs=yes; shift 1;;
	--url|--trees|--distrotrees) getdistrotrees=yes; shift 1;;
	--rpmsinfo) getrpmsinfo=yes; shift 1;;
	--composeinfo) getcomposeinfo=yes; shift 1;;
	--dbroot) dbroot=$2; shift 2;;
	--dlist|--distrolist) getdistrolist=yes; shift 1;;
	--) shift; break;;
	esac
done

dbpath=$dburl
if [[ -d $dbroot ]]; then
	dbpath=file://$(readlink -f $dbroot)
fi
Debug "using data source: $dbpath"

[[ -n "$getdistrolist" ]] && {
	curl -Lsf $dbpath/distro.list
	exit $?
}

Pkg=${Pkg:-$1}
RawPkg=$Pkg
Pkg=${Pkg:-^kernel-[0-9]}
[[ ${Pkg} != ^* ]] && Pkg="[^/]*${Pkg}" || Pkg=${Pkg:1}
[[ ${Pkg} != *$ ]] && Pkg="${Pkg}[^/]*" || Pkg=${Pkg:0:-1}
Distro=${Distro:-$2}
Distro=${Distro#/}

[[ -n "$Distro" ]] && {
	if [[ "$Distro" = *[%*]* ]]; then
		Distro=$(bkr distros-list --limit=0 --name "$Distro" | awk '$1 == "Name:" {print $2}' | sort -Vr | head -1)
	fi
	cachefile=$dbpath/${Distro// /_}.json.gz
	distrotrees_file=$dbpath/${Distro// /_}.distrotrees.gz

	[[ -n "$getrpmsinfo" ]] && {
		if curl --output /dev/null --silent --fail -r 0-0 "$cachefile"; then
			curl -Lsf $cachefile | zcat 2>/dev/null
			ret=$?
		else
			echo "{warn} ${Distro}'s info has not been synced to database, try bkr sub-command ..." >&2
			if bkr whoami &>/dev/null; then
				distrotrees=$(bkr distro-trees-list --limit=0 --name "$Distro")
				urls=$(echo "$distrotrees" |
					awk '/https?:/ {
						if ($3 ~ "/compose/") {
							sub("/compose/.*$", "/compose/metadata", $3)
						} else if ($3 ~ "/released/rhel-4-5/") {
							sub("([^/]+/){2}$", "metadata", $3)
						} else if ($3 ~ "/released/") {
							sub("([^/]+/){3}$", "metadata", $3)
						} else {
							rc=1
						}
						if (rc != 1) {print $3}
					}' | sort -u)

				for url in $urls; do
					[[ "$url" =~ RHEL-?5 ]] && continue
					if curl -sf -k -L -u: $url/rpms.json ||
						curl -sf -k -L -u: $url/rpm-manifest.json; then
						ret=0
						break
					else
						echo "{warn} get rpm json file of '$Distro' fail: $url" >&2
						ret=1
					fi
				done
			else
				echo "{warn} exec 'bkr whoami' fail ..." >&2
				ret=1
			fi
		fi
		exit $ret
	}

	[[ -n "$getlabs" ]] && {
		if bkr whoami &>/dev/null; then
			bkr distro-trees-list --limit=0 --name "$Distro"|
				awk '/^ *lab/ {n=split($1,a,"."); print a[n-2]}' |
				sort -u | paste -sd ,
		else
			curl -Lsf $distrotrees_file | zcat 2>/dev/null|
				awk '/^ *lab/ {n=split($1,a,"."); print a[n-2]}' |
				sort -u | paste -sd ,
		fi
		exit $?
	}

	[[ -n "$getdistrotrees" ]] && {
		if curl --output /dev/null --silent --fail -r 0-0 "$distrotrees_file"; then
			curl -Lsf $distrotrees_file | zcat 2>/dev/null
			ret=$?
		else
			echo "{warn} ${Distro}'s info has not been synced to database, try bkr distro-trees-list ..." >&2
			if bkr whoami &>/dev/null; then
				bkr distro-trees-list --limit=0 --name "$Distro"
				ret=$?
			else
				echo "{warn} exec 'bkr whoami' fail ..." >&2
				ret=1
			fi
		fi
		exit $ret
	}

	[[ -n "$getcomposeinfo" ]] && {
		urls=$(curl -Lsf $distrotrees_file | zcat 2>/dev/null |
			awk '/https?:/ {
				if ($3 ~ "/compose/") {
					sub("/compose/.*$", "/compose/metadata", $3)
				} else if ($3 ~ "/released/") {
					sub("([^/]+/){3}$", "metadata", $3)
				}
				print $3
			}' | sort -u)
		for url in $urls; do
			curl -Lsf $url/composeinfo.json && break
		done
		exit $?
	}
}

[[ -z "${Pkg}" && "$Update" != yes ]] && {
	Usage
	exit 1
}

Debug "pkg:($Pkg) distro:($Distro) arch:($Arch) variant:($Variant)"
case "$Arch" in
	x86_64|i386|ppc64le|ppc64|s390x|aarch64) :;;
	*) echo "{warn} unknow arch '$Arch'" >&2;;
esac

# do search
mylist=$(curl -Lsf $dbpath/distro.list > >(egrep -i -- "${Distro}"))
ret=$?
[[ $ret != 0 ]] && {
	echo "something is wrong, curl return code $ret" >&2
}
while read distro; do
	[[ -z "$distro" ]] && continue
	cachefile=$dbpath/${distro// /_}.json.gz

	variant=$Variant
	read _ VX _ <<< "${distro//[-.]/ }"
	[[ $VX -ge 8 ]] && {
		case $variant in Workstation|Client|Server|ComputeNode) variant=;; esac
	}
	[[ $distro = [Ff]edora* ]] && variant=Everything

	Debug "distro:($distro) pkg:($Pkg) arch:($Arch) variant:($variant) @$cachefile"
	#_result=$(curl -Lsf $cachefile | zcat 2>/dev/null |
	#	jq -r '.payload | with_entries(if .key == "manifest" then .key = "rpms" else . end)|.rpms|'".${variant:-[]}|.$Arch|.[]|.[].path" |
	#	grep -v source/tree |
	#	egrep "$Pkg")
	if [[ $distro =~ RHEL-?5 ]]; then
		distrotrees_file=$dbpath/${distro// /_}.distrotrees.gz
		read _ _ url _ < <(curl -Lsf $distrotrees_file | zcat 2>/dev/null | egrep https?://.*bos)
		Debug "egrep -o \">${RawPkg}-[0-9a-z\\._-]+\\.rpm<\" < <(curl -Lsf $url/Server)"
		_result=$(egrep -o ">${RawPkg}-[0-9a-z\._-]+\.rpm<" < <(curl -Lsf $url/Server) | sed -e 's/^>//' -e 's/<$//')
	else
		Debug "egrep -o -i \"${variant:-[^\\\"]+}/($Arch)/os/(Packages|$variant)/([a-z]/)?(${Pkg})\.[0-9a-z_-]+\.rpm\" < <(curl -Lsf $cachefile|zcat 2>/dev/null)"
		_result=$(egrep -o -i "${variant:-[^\"]+}/($Arch)/os/(Packages|$variant)/([a-z]/)?(${Pkg})\.[0-9a-z_-]+\.rpm" < <(curl -Lsf $cachefile|zcat 2>/dev/null))
	fi
	[[ -n "$_result" ]] && {
		[[ -z "$nocolor" ]] && echo -e "=> \033[1;34m$distro\033[0m" || echo -n "$distro -> "
		if [[ $long = yes ]]; then
			result=$(echo "$_result"|sed -r -e 's/^/    /' -e 's/\.[^.]+\.rpm//')
		else
			result=$(echo "$_result"|sed -r -e 's;.*/;;' -e 's/\.[^.]+\.rpm//')
		fi

		if [[ "$oneline" = yes ]]; then
			echo "$result" | head -n $maxperline | xargs
		else
			echo "$result"
		fi
	}
done <<<"$mylist"

