#!/bin/bash
#author jiyin@redhat.com

baseDownloadUrl=https://raw.githubusercontent.com/tcler/bkr-client-improved/master

is_intranet() {
	local iurl=http://download.devel.redhat.com
	curl --connect-timeout 5 -m 10 --output /dev/null --silent --head --fail $iurl &>/dev/null
}

is_intranet && {
	Intranet=yes
	baseDownloadUrl=http://download.devel.redhat.com/qa/rhts/lookaside/bkr-client-improved
}

# install brew
which brew &>/dev/null || {
	which brewkoji_install.sh || {
		_url=$baseDownloadUrl/utils/brewkoji_install.sh
		mkdir -p ~/bin && wget -O ~/bin/brewkoji_install.sh -N -q $_url
		chmod +x ~/bin/brewkoji_install.sh
	}
	brewkoji_install.sh >/dev/null || {
		echo "{WARN} install brewkoji failed" >&2
		exit 1
	}
}

run() {
	local cmdline=$1
	local ret=0

	echo "[$(date +%T) $USER@ ${PWD%%*/}]# $cmdline"
	eval $cmdline
	ret=$?

	return $ret
}

Usage() {
	echo "Usage: $0 <build_id> <store_path> [--arch=|-c|-h]"
}

_at=`getopt -o ch --long arch: --long help -n "$0" -- "$@"`
eval set -- "$_at"
while true; do
	case "$1" in
	-h|--help)      Usage; shift 1; exit 0;;
	--arch)         arch=$2; shift 2;;
	-c)		createrepo=yes; shift 1;;
	--) shift; break;;
	esac
done

# arg parse
[ $# -lt 2 ] && { Usage; exit 1; }

taskid=$1
storepath=$2
[[ $taskid =~ ^[0-9]+$ ]] || {
	echo "Warn: invalide build_id: '$taskid'"
	Usage
	exit 1
}

# Download packges
[ -d "$storepath" ] || {
	echo "Info: '$storepath' does not exist, create it."
	mkdir -p "$storepath" || {
		exit 1
	}
}
mkdir -p $storepath/$taskid

pushd $storepath/$taskid &>/dev/null
	#wait the scratch build finish
	while brew taskinfo $taskid|grep -q '^State: open'; do echo "[$(date +%T) Info] build hasn't finished, waiting ..."; sleep 5m; done

	run "brew taskinfo -r $taskid > >(tee brew_buildinfo.txt)"
	urllist=$(sed -n '/mnt.redhat..*rpm$/{s; */mnt/redhat/;; ; p}' brew_buildinfo.txt|sort -u)
	[ -n "$arch" ] && urllist=$(echo "$urllist" | egrep "\\.($arch|noarch)\\.rpm")
	echo "$urllist"
	for url in $urllist; do
		#echo "http://download.devel.redhat.com/$url"
		run "wget -c --progress=dot:mega http://download.devel.redhat.com/$url"
	done

	# Install packages
	run "ls -lh"
popd &>/dev/null

