#!/bin/bash

run() {
	local cmdline=$1
	local ret=0

	echo "[$(date +%T) $USER@ ${PWD%%*/}]# $cmdline"
	eval $cmdline
	ret=$?

	return $ret
}

# Install koji & brew
installBrew2() {
	#https://mojo.redhat.com/docs/DOC-1024827
	urls="
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-6-server.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-6-client.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-6-workstation.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-server.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-client.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-7-workstation.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-8-baseos.repo
	curl -L -O http://download.devel.redhat.com/rel-eng/internal/rcm-tools-fedora.repo
	"

	local name=$(lsb_release -sir|awk '{print $1}')
	local verx=$(lsb_release -sr|awk -F. '{print $1}')

	pushd /etc/yum.repos.d
	case $name in
	RedHatEnterprise*)
		case $verx in
		6|7) 
			for type in server client workstation; do
				curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-${verx}-${type}.repo
				yum install -y koji brewkoji && break || rm rcm-tools-*.repo
			done
			;;
		8)
			curl -L -O http://download.devel.redhat.com/rel-eng/RCMTOOLS/rcm-tools-rhel-8-baseos.repo
			yum install -y koji brewkoji python3-koji python3-pycurl || rm rcm-tools-*.repo
			;;
		esac
		;;
	Fedora*)
		curl -L -O http://download.devel.redhat.com/rel-eng/internal/rcm-tools-fedora.repo
		yum install -y koji brewkoji
		;;
	esac
	popd

	which brew &>/dev/null
}
installBrewFromSourceCode() {
	git -c http.sslVerify=false clone  https://code.engineering.redhat.com/gerrit/rcm-brewkoji.git
	cd rcm-brewkoji
	make install >/dev/null

	which brew &>/dev/null
}

Usage() {
	echo "Usage: $0 <build_id> <store_path> [--arch=|-c|-h]"
}

_at=`getopt -o ch --long arch: --long help -n "$0" -- "$@"`
eval set -- "$_at"
while true; do
	case "$1" in
	-h|--help)      Usage; shift 1; exit 0;;
	--arch)         arch=$2; shift 2;;
	-c)		createrepo=yes; shift 1;;
	--) shift; break;;
	esac
done

# arg parse
[ $# -lt 2 ] && { Usage; exit 1; }

taskid=$1
storepath=$2
[[ $taskid =~ ^[0-9]+$ ]] || {
	echo "Warn: invalide build_id: '$taskid'"
	Usage
	exit 1
}

# fix ssl certificate verify failed
curl https://password.corp.redhat.com/RH-IT-Root-CA.crt -o /etc/pki/ca-trust/source/anchors/RH-IT-Root-CA.crt
curl https://password.corp.redhat.com/legacy.crt -o /etc/pki/ca-trust/source/anchors/legacy.crt
update-ca-trust

yum --setopt=strict=0 install -y koji python-koji python-pycurl brewkoji

# install koji & brew
which brew &>/dev/null || installBrew2 || installBrewFromSourceCode

# Download packges
[ -d "$storepath" ] || {
	echo "Info: '$storepath' does not exist, create it."
	mkdir -p "$storepath" || {
		exit 1
	}
}
mkdir -p $storepath/$taskid

pushd $storepath/$taskid &>/dev/null
	#wait the scratch build finish
	while brew taskinfo $taskid|grep -q '^State: open'; do echo "[$(date +%T) Info] build hasn't finished, waiting ..."; sleep 5m; done

	run "brew taskinfo -r $taskid > >(tee brew_buildinfo.txt)"
	urllist=$(sed -n '/mnt.redhat..*rpm$/{s; */mnt/redhat/;; ; p}' brew_buildinfo.txt|sort -u)
	[ -n "$arch" ] && urllist=$(echo "$urllist" | egrep "\\.($arch|noarch)\\.rpm")
	echo "$urllist"
	for url in $urllist; do
		#echo "http://download.devel.redhat.com/$url"
		run "wget -c --progress=dot:mega http://download.devel.redhat.com/$url"
	done

	# Install packages
	run "ls -lh"
popd &>/dev/null

