#!/bin/bash
# Kerberos ticket will never be expired
# author: zhchen@redhat.com

username=$1
read -s -p "Password: " password
echo

_kinit() {
	#for macOS
	if kinit -h 2>&1 | grep -q password-file=; then
		kinit_opt=--password-file=STDIN
	fi
	echo $password | kinit $kinit_opt $username >/dev/null
}

forever_kinit() {
	local cycle=2
	while : ; do
		sleep $((60 * 60 * 8))
		for ((i=0; i<512; i++)); do
			_kinit
			if [[ $? = 0 ]]; then
				break
			else
				echo "[$(date)] kinit fail, try again $cycle seconds later"
				sleep $cycle
			fi
		done
	done
}

# make sure password is correct
_kinit || exit 1

# then function can run in background forever, untill you kill it
trap "" HUP
forever_kinit & pid=$!

# save pid, in case you want to kill it easily
echo -n "Succeed! running forever_kinit in background, pid is: "
echo $pid | tee /tmp/klogin-$USER.pid

# and the script can exit.
exit 0
