#!/bin/bash

nick=testBot
line=${1/$'\r'/}
color=$2

# https://en.wikichip.org/wiki/irc/colors
ircBold=$'\x02'
ircItalics=$'\x1D'
ircUnderline=$'\x1F'
ircReverse=$'\x16'
ircPlain=$'\x0F'

ircWhite=$'\x03'00
ircBlack=$'\x03'01
ircNavy=$'\x03'02
ircGreen=$'\x03'03
ircRed=$'\x03'04
ircMaroon=$'\x03'05
ircPurple=$'\x03'06
ircOlive=$'\x03'07
ircYellow=$'\x03'08
ircLightGreen=$'\x03'09
ircTeal=$'\x03'10
ircCyan=$'\x03'11
ircRoyalblue=$'\x03'12
ircMagenta=$'\x03'13
ircGray=$'\x03'14
ircLightGray=$'\x03'15

grep -i -q "Sorry, I can't find distro '" <<<"$line" && {
	line=$(echo "${line}"|sed -r -e "s/.*Sorry, I can't find distro '(.+)'.*/\1/")
	[[ "$line" = [0-9]* ]] && line=RHEL-$line
	line="${line} $nick";
}
grep -i -q $nick <<<"$line" || exit

[[ "${line,,}" =~ help ]] && {
	echo "
usage0: (bz|bug )\$bugid or bug url  $nick   # get bug info
usage1: <\$distro_list>   $nick   # get kernel versions of \$distro_list
usage2: pkg <pkg_name_list> <distro_name_list>   $nick # check default package version in specified distro"
	exit 0
}

[[ "${line,,}" =~ thx|thank ]] && {
	echo 'you are welcome!'
	exit 0
}

for word in ${line//,/ }; do
	case ${word,,} in
	cc|${nick,,}*) :;;
	[^a-zA-Z0-9^]*) :;;
	pkg)        PKG=yes;;
	rhel[-%]*)  distros+=(RHEL-${word:5});;
	fedora-*)   distros+=(Fedora-${word:7});;
	*) [[ ${#word} -ge 2 ]] && pkgs+=($word);;
	esac
done

[[ x"$PKG" != xyes ]] && pkgs=("^kernel-(rt-)?[0-9]")
for distro in ${distros[@]}; do
	for pkgn in ${pkgs[@]}; do
		if [[ "$color" = color* ]]; then
			distro-compose -n -p "$pkgn" -d "$distro" -as390x --oneline | head -n2 |
				sed -r -e "s/-[^ ]+/${ircBold}&${ircPlain}/" -e "s/${pkgn//[\^$]/}/${ircRed}&${ircPlain}/g"
		else
			distro-compose -n -p "$pkgn" -d "$distro" -as390x --oneline | head -n2 |
				sed -r -e "s/-[^ ]+/${ircBold}&${ircPlain}/"
		fi
	done
done

bugs=$(egrep -i -o '(bug *|bz|bugzilla.redhat.com.*id=)[0-9]+\>' <<<"$line"|sed -r 's/(bug *|bz|bugzilla.redhat.com.*id=)//I')
while read bug; do
	[[ -z "$bug" ]] && continue
	bugzilla query -b ${bug}
done <<<"$bugs"
exit 0
