#!/usr/bin/expect
# auto ssh login beaker machine with root
# Author: Zhenjie Chen <zhchen@redhat.com>

set timeout 120
set conf ~/.bkr_prefs.tcl

if ![file exist $conf] {
	puts "Could not find config file to read password"
	exec echo "set PASSWD {xxxxx}" > $conf
	puts "Initialized $conf, please modify it and retry"
	exit 1
}

source $conf
# read password setting from "~/.bkr_prefs.tcl"
# config file might look like:
#	set PASSWD {xxxxxx}

set USER root
set SERVER [lindex $argv 0]
set sshOpt [lrange $argv 1 end]

spawn bash -c "TERM=xterm ssh $sshOpt -l $USER $SERVER \
-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

expect {
"password:" { send "${PASSWD}\r" }
"*#" {send "\r"}
}
expect {
"password:" { send "redhat\r" }
"*#" {send "\r"}
}
interact
