#!/bin/bash
#author: jiyin@redhat.com

P=${0##*/}

usage() {
	echo "usage: $0  <ver1> < =  | '>' | '<' | '>=' | '<=' >  <ver2>" >&2
	echo "       $0  <ver1> < eq | gt  | lt  |  ge  |  le  >  <ver2>" >&2
	echo "       $0  <ver1> < match >  <'pattern'>" >&2
}

sortV() {
	if echo | sort -V &>/dev/null; then
		cat - | sort -V "$@"
	else
		if ! echo "$@" | grep -E -q '( |^)-r( |$)'; then
			cat - | sed -r -e 's/^/k-/' -e "s/-([0-9]+\.)/.\1/" -e "s/-([0-9]+\.)/-.\1/" |
			sort -t . -k1,1 -k2,2n -k3,3n -k4,4n -k5,5n -k6,6n |
			sed -r -e "s/\./-/" -e "s/-\./-/" -e 's/^k.//'
		else
			cat - | sed -r -e 's/^/k-/' -e "s/-([0-9]+\.)/.\1/" -e "s/-([0-9]+\.)/-.\1/" |
			sort -t . -k1,1 -k2,2n -k3,3n -k4,4n -k5,5n -k6,6n | tac |
			sed -r -e "s/\./-/" -e "s/-\./-/" -e 's/^k.//'
		fi
	fi
}

vercmp() {
	[ $# != 3 ] && {
		usage
		return 1
	}
	vl=$1
	cmpType=$2
	vr=$3
	res=1

	[ "$vl" = "$vr" ] && eq=1
	vmax=$(echo -e "$vl\n$vr" | sortV | tail -n 1)

	case "$cmpType" in
	=|eq) [ "$eq" = 1 ] && res=0;;
	\>|gt) [ "$eq" != 1 -a "$vl" = "$vmax" ] && res=0;;
	\<|lt) [ "$eq" != 1 -a "$vr" = "$vmax" ] && res=0;;
	\>=|ge) [ "$vl" = "$vmax" ] && res=0;;
	\<=|le) [ "$vr" = "$vmax" ] && res=0;;
	*) echo "$vl" | grep -E -q "$vr"; res=$?;;
	esac

	return $res
}

case $P in
sortV) sortV "$@";;
*) vercmp "$@";;
esac
